### ISSUE TITLE
Do plugins belong in this repository?

### ISSUE THREAD

**Issue by joallard** [selectize/selectize.js#976]
PRs and issues about proposed plugins put a toll on the triage process. As we are picking back up this project and working to clear the issue backlog, I got thinking about how plugins are hosted and integrated. In the past, it seems we accepted PRs to integrate people's plugins into the `src/plugins` folder. That means not only do the maintainers need to negotiate and approve the addition of plugins, but they also need to process issues pertaining to them, accept fixes, etc.

I think that this repo shouldn't be a barrier to people publishing their plugins. People should be able to publish a repository of their own. The Selectize organization could also be able to host and maintain popular plugins under its umbrella.

How we should facilitate this process:
- [ ] Add documentation about how to structure and name a repo (eg. selectize-restore-on-backspace)
- [ ] Add a plugin directory (first simply in the wiki, then we can get to fancier options)
- [ ] Export `src/plugins` to org. repos

Sounds good?
cc @brianreavis

**Comment by brianreavis** [comment]
Sounds epic @joallard. All for it :+1:

**Comment by Samsinite** [comment]
Sounds like a good solution :)

**Comment by Pictor13** [comment]
Seems like it would give additional freedom and open more to contribution. That's nice! :+1: 

Btw thanks for your work

**Comment by RohovDmytro** [comment]
Great.

**Comment by Pictor13** [comment]
Any news about that?
Would be great to be able to create/load own custom plugins, without need to have them approved/pulled in the official repository.
